version: "3.3"

services:

  composer:
    image: composer
    volumes:
      - "./:/app"
    working_dir: /app
    command: install

  phpunit:
    image: php:7.2-cli
    volumes:
      - "./:/app"
    working_dir: /app
    command: ./vendor/bin/phpunit -v --bootstrap vendor/autoload.php --testdox tests